name: CI/CD for Express.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Operating System
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # This action checks out your repository so your workflow can access it

      - name: Set up Node.js
        uses: actions/setup-node@v3 # This action sets up a version of Node.js for use in actions by adding to PATH
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy when the main branch is updated
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # This action checks out your repository so your workflow can access it

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --production # Install only production dependencies


      # - name: Deploy to Server
      #   env:
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #     SSH_USER: ${{ secrets.SSH_USER }}
      #     SSH_KEY: ${{ secrets.SSH_KEY }}
      #   run: |
      #     echo "$SSH_KEY" > deploy_key.pem
      #     chmod 600 deploy_key.pem
      #     ssh -i deploy_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
      #       cd /var/www/express
      #       git pull origin main
      #       npm install --production
      #       pm2 restart all
      #     EOF
